#ifndef DASHBOARDMAIN_CALLBACKS_H
#define DASHBOARDMAIN_CALLBACKS_H

#include "gui_api.h"
#include "gui_text.h"
#include "gui_obj_focus.h"

// Timer animation counters (defined in callbacks.c)
extern uint16_t gloom_timer_cnt;
extern uint16_t dashboard_view_timer_cnt;
extern uint16_t map_timer_cnt;
extern uint16_t win_func_timer_cnt;
extern uint16_t win_app_list_timer_cnt;
extern uint16_t app_list_timer_cnt;
extern uint16_t tab_hightlight_timer_cnt;
extern uint16_t win_app_weather_timer_cnt;
extern uint16_t list_weather_timer_cnt;
extern uint16_t win_app_developing_timer_cnt;
extern uint16_t root_menu_timer_cnt;
extern uint16_t win_dail_timer_cnt;
extern uint16_t speed_arc_timer_cnt;
extern uint16_t dail_pointer_s_timer_cnt;
extern uint16_t power_arc_timer_cnt;
extern uint16_t dail_pointer_p_timer_cnt;
extern uint16_t win_common_timer_cnt;
extern uint16_t turn_l_icon_timer_cnt;
extern uint16_t turn_r_icon_timer_cnt;
extern uint16_t text_time_timer_cnt;
extern uint16_t led_0_timer_cnt;
extern uint16_t led_1_timer_cnt;
extern uint16_t led_2_timer_cnt;
extern uint16_t led_3_timer_cnt;
extern uint16_t led_4_timer_cnt;
extern uint16_t led_5_timer_cnt;
extern uint16_t win_speed_text_timer_cnt;
extern uint16_t text_speed_timer_cnt;
extern uint16_t text_odo_timer_cnt;
extern uint16_t win_power_text_timer_cnt;
extern uint16_t text_power_timer_cnt;
extern uint16_t text_battery_timer_cnt;
extern uint16_t win_volume_timer_cnt;
extern uint16_t lbl_volume_timer_cnt;
extern uint16_t win_music_timer_cnt;
extern uint16_t win_carplay_timer_cnt;
extern uint16_t carplay_time_timer_cnt;
extern uint16_t carplay_speed_arc_timer_cnt;
extern uint16_t win_music_bar_timer_cnt;

// Event callback function declarations
void carplay_view_key_0_cb(void *obj, gui_event_t *e);
void dail_power_clicked_cb(void *obj, gui_event_t *e);
void root_menu_key_cb(void *obj, gui_event_t *e);
void start_engine_key_cb(void *obj, gui_event_t *e);
void win_app_developing_key_0_cb(void *obj, gui_event_t *e);
void win_app_list_key_0_cb(void *obj, gui_event_t *e);
void win_app_weather_key_0_cb(void *obj, gui_event_t *e);
void win_carplay_msg_cb_0(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_carplay_msg_cb_1(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_carplay_msg_cb_2(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_carplay_msg_cb_3(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_carplay_msg_cb_4(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_carplay_msg_cb_5(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_carplay_msg_cb_6(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_0(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_1(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_10(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_11(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_12(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_13(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_14(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_15(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_16(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_2(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_3(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_4(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_5(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_6(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_7(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_8(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_common_msg_cb_9(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_dail_msg_cb_0(gui_obj_t *obj, const char *topic, void *data, uint16_t len);
void win_dail_msg_cb_1(gui_obj_t *obj, const char *topic, void *data, uint16_t len);

// User-configured timer callback function declarations
void gloom_timer_0_cb(void *obj);
void dashboard_entrance_timer_0_cb(void *obj);
void map_timer_0_cb(void *obj);
void map_timer_1_cb(void *obj);
void win_func_timer_0_cb(void *obj);
void win_func_timer_1_cb(void *obj);
void win_app_list_timer_0_cb(void *obj);
void win_app_list_timer_1_cb(void *obj);
void app_list_timer_0_cb(void *obj);
void app_list_timer_1_cb(void *obj);
void tab_hightlight_timer_0_cb(void *obj);
void win_app_weather_timer_0_cb(void *obj);
void win_app_weather_timer_1_cb(void *obj);
void list_weather_timer_0_cb(void *obj);
void win_app_developing_timer_0_cb(void *obj);
void win_app_developing_timer_1_cb(void *obj);
void root_menu_timer_0_cb(void *obj);
void root_menu_timer_1_cb(void *obj);
void root_menu_timer_2_cb(void *obj);
void root_menu_timer_3_cb(void *obj);
void root_menu_timer_4_cb(void *obj);
void root_menu_timer_5_cb(void *obj);
void root_menu_timer_6_cb(void *obj);
void root_menu_timer_7_cb(void *obj);
void root_menu_timer_8_cb(void *obj);
void root_menu_timer_9_cb(void *obj);
void root_menu_timer_10_cb(void *obj);
void root_menu_timer_11_cb(void *obj);
void win_dail_timer_0_cb(void *obj);
void win_dail_timer_1_cb(void *obj);
void win_dail_timer_2_cb(void *obj);
void speed_arc_timer_0_cb(void *obj);
void dail_pointer_s_timer_0_cb(void *obj);
void power_arc_timer_0_cb(void *obj);
void dail_pointer_p_timer_0_cb(void *obj);
void win_common_timer_0_cb(void *obj);
void turn_l_icon_timer_0_cb(void *obj);
void turn_r_icon_timer_0_cb(void *obj);
void text_time_timer_0_cb(void *obj);
void led_0_timer_0_cb(void *obj);
void led_1_timer_0_cb(void *obj);
void led_2_timer_0_cb(void *obj);
void led_3_timer_0_cb(void *obj);
void led_4_timer_0_cb(void *obj);
void led_5_timer_0_cb(void *obj);
void win_speed_text_timer_0_cb(void *obj);
void win_speed_text_timer_1_cb(void *obj);
void win_speed_text_timer_2_cb(void *obj);
void text_speed_timer_0_cb(void *obj);
void text_speed_timer_1_cb(void *obj);
void text_odo_timer_0_cb(void *obj);
void win_power_text_timer_0_cb(void *obj);
void win_power_text_timer_1_cb(void *obj);
void win_power_text_timer_2_cb(void *obj);
void text_power_timer_0_cb(void *obj);
void text_power_timer_1_cb(void *obj);
void text_battery_timer_0_cb(void *obj);
void win_volume_timer_0_cb(void *obj);
void lbl_volume_timer_0_cb(void *obj);
void win_music_timer_0_cb(void *obj);
void carplay_entrance_timer_0_cb(void *obj);
void carplay_speed_timer_0_cb(void *obj);
void carplay_music_timer_0_cb(void *obj);

// Custom function declarations (auto-extracted from callbacks.c protected area)
void text_odo_timer_0_cb(void *obj);
void text_battery_timer_0_cb(void *obj);
void text_speed_timer_0_cb(void *obj);
void text_speed_timer_1_cb(void *obj);
void text_power_timer_0_cb(void *obj);
void text_power_timer_1_cb(void *obj);
void text_time_timer_0_cb(void *obj);
void zoom_animation(gui_obj_t *obj, float scale);
void win_speed_text_timer_0_cb(void *obj);
void win_power_text_timer_0_cb(void *obj);
void tab_hightlight_timer_0_cb(void *obj);
void app_list_timer_0_cb(void *obj);
void app_list_timer_1_cb(void *obj);
void list_weather_timer_0_cb(void *obj);
void lbl_volume_timer_0_cb(void *obj);
void win_music_timer_0_cb(void *obj);
void carplay_music_timer_0_cb(void *obj);
void dashboard_entrance_timer_0_cb(void *obj);
void carplay_speed_timer_0_cb(void *obj);
void carplay_entrance_timer_0_cb(void *obj);

#endif // DASHBOARDMAIN_CALLBACKS_H
